[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
dkg_tcp = { path = ".." }
futures = "0.3"
tokio = { version = "1.33", features = ["full"] }
givre = { version = "0.2.0", features = ["cggmp21-keygen", "ciphersuite-ed25519", "full-signing", "serde"] }
anyhow = "1.0.100"
round-based = "0.4.1"
sha2 = "0.10.9"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
hex = "0.4.3"
serde_json = "1.0.145"
bs58 = "0.5.1"

solana-sdk = "3.0.0"
solana-program = "3.0.0"
borsh = "1.5.7"
solana-instruction = "3.0.0"
solana-keypair = "3.0.1"
solana-message = "3.0.1"
solana-pubkey = "3.0.0"
solana-rpc-client = "3.0.8"
solana-signer = "3.0.0"
solana-transaction = "3.0.1"
solana-system-program = "3.0.8"
#kafka = "0.10.0"
#openssl = { version = "0.10", features = ["vendored"] }

