[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
dkg_tcp = { path = ".." }
futures = "0.3"
tokio = { version = "1.33", features = ["full"] }
givre = { version = "0.2.0", features = ["cggmp21-keygen", "ciphersuite-ed25519"] }
anyhow = "1.0.100"
round-based = "0.4.1"
sha2 = "0.10.9"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }